# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('q1_val', models.IntegerField(default=0)),
                ('q2_val', models.IntegerField(default=0)),
                ('q3_val', models.IntegerField(default=0)),
                ('q4_val', models.IntegerField(default=0)),
                ('q5_val', models.IntegerField(default=0)),
                ('q6_val', models.IntegerField(default=0)),
                ('q7_val', models.IntegerField(default=0)),
                ('q8_val', models.IntegerField(default=0)),
                ('q9_val', models.IntegerField(default=0)),
                ('q10_val', models.IntegerField(default=0)),
                ('q11_val', models.IntegerField(default=0)),
                ('q12_val', models.IntegerField(default=0)),
                ('q13_val', models.IntegerField(default=0)),
                ('q14_val', models.IntegerField(default=0)),
                ('q15_val', models.IntegerField(default=0)),
                ('q16_val', models.IntegerField(default=0)),
                ('q17_val', models.IntegerField(default=0)),
                ('q18_val', models.IntegerField(default=0)),
                ('q19_val', models.IntegerField(default=0)),
                ('q20_val', models.IntegerField(default=0)),
            ],
        ),
    ]
